import type { Metadata } from "next";
import "./globals.css";
import Navbar, { AdminNavbar } from "@/components/navbar";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Bazar Komplek",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let adminPage = false;
  let logOn = false;
  const isAdmin = cookies().get("isAdmin");
  const cookie = cookies().get("Authorization");

  if (isAdmin?.name) adminPage = true;
  if (cookie?.name) logOn = true;

  return (
    <html lang="en">
      <body className="bg-white">
        {adminPage ? <AdminNavbar /> : <Navbar logOn={logOn} />}
        {children}
      </body>
    </html>
  );
}
